#!/usr/bin/env python3
"""Regenerate tests/xtensa/opcodes.txt from the coverage dumps.

1. cargo test --no-default-features --bin trmnl-sim opcode_coverage
   (recursive-descent scan of firmware.elf and the ROM with our decoder; writes
   target/xtensa-coverage-*.txt)
2. python3 tests/xtensa/scripts/compare_objdump.py   (validates our names vs objdump)
3. python3 tests/xtensa/scripts/make_opcode_fixture.py

The fixture lists every mnemonic reachable in the firmware and ROM with its count and up
to 4 example encodings (little-endian bytes); the `opcode_fixture_decodes` test checks
each still decodes to that mnemonic, so CI covers this without the ELFs.
"""
import os, collections

ROOT = os.path.join(os.path.dirname(__file__), "..", "..", "..")
counts = collections.defaultdict(lambda: [0, 0, 0])
examples = collections.defaultdict(list)
for idx, name in enumerate(["firmware", "rom", "bootloader"]):
    path = os.path.join(ROOT, "target", f"xtensa-coverage-{name}.txt")
    if not os.path.exists(path):
        continue
    for line in open(path):
        if line.startswith("# "):
            _, mn, n = line.split()
            counts[mn][idx] += int(n)
            continue
        pc, ln, raw, dis = line.rstrip("\n").split(" ", 3)
        mn = dis.split("\t")[0]
        ln = int(ln)
        le = int(raw, 16).to_bytes(ln, "little").hex()
        if len(examples[mn]) < 4 and le not in examples[mn]:
            examples[mn].append(le)

out = ["# mnemonic  example-encoding(LE hex)   [firmware-count rom-count bootloader-count]",
       "# Generated by tests/xtensa/scripts/make_opcode_fixture.py from a recursive-descent",
       "# scan of TRMNL_X firmware.elf, bootloader.elf and esp32s3_rev0_rom.elf. Entries decoded only on",
       "# paths after noreturn calls (padding) are excluded."]
for mn in sorted(counts):
    if mn.startswith(".unknown") or mn in ("xsr", "rsr", "wsr"):
        continue
    fw, rom, bl = counts[mn]
    for e in examples[mn]:
        out.append(f"{mn} {e}   {fw} {rom} {bl}")
open(os.path.join(ROOT, "tests", "xtensa", "opcodes.txt"), "w").write("\n".join(out) + "\n")
print(f"{len([m for m in counts if not m.startswith('.')])} mnemonics")
