//! The contract between the emulator thread and front-ends (GUI, headless CLI).
//! Front-ends only see this module; they never touch the machine directly.

use std::collections::VecDeque;
use std::sync::Arc;

use crossbeam_channel::{Receiver, Sender};
use parking_lot::Mutex;

/// What the viewer sees on the e-paper: per-pixel darkness 0 (white) ..= 255 (black).
#[derive(Clone)]
pub struct Frame {
    pub width: usize,
    pub height: usize,
    pub pixels: Vec<u8>,
    /// Bumped whenever `pixels` changes.
    pub generation: u64,
}

pub type SharedFrame = Arc<Mutex<Frame>>;

/// Requests from the front-end to the emulator thread.
#[derive(Debug, Clone)]
pub enum Command {
    /// The physical button is held down (true) or released (false).
    Button(bool),
    /// Press the button and release it after exactly this many milliseconds of
    /// virtual time (precise even when running faster or slower than real time).
    Press {
        ms: u64,
    },
    /// Battery voltage in millivolts.
    SetBatteryMv(u32),
    /// Press the reset button (chip reset, RTC memory and display kept).
    Reset,
    /// Remove and restore power: RTC memory is lost; flash and display are kept.
    PowerCycle,
    /// End a deep/light sleep now, as if its timer expired.
    WakeFromSleep,
    /// Enable/disable the simulated access point the device joins.
    SetWifiAvailable(bool),
    /// Run as fast as possible (true) or pace to wall-clock time (false).
    SetTurbo(bool),
    Pause(bool),
    Quit,
}

#[derive(Debug, Clone, PartialEq)]
pub enum RunState {
    Running,
    Paused,
    /// Waiting for an interrupt (FreeRTOS idle); still "awake".
    Idle,
    LightSleep {
        wake_at_ns: Option<u64>,
    },
    DeepSleep {
        wake_at_ns: Option<u64>,
    },
    /// The emulator stopped: CPU exception, unimplemented feature, etc.
    Halted(String),
}

#[derive(Debug, Clone)]
pub struct Status {
    pub state: RunState,
    /// Virtual time since power-on, in nanoseconds.
    pub sim_time_ns: u64,
    /// Emulation speed in millions of guest instructions per second.
    pub mips: f64,
    /// Virtual time / wall time over the last second (1.0 = realtime).
    pub speed_ratio: f64,
    pub battery_mv: u32,
    pub button_down: bool,
    pub wifi_available: bool,
    pub wifi_connected: bool,
    pub ip: Option<String>,
    /// Host URL of the device's captive portal while it runs its setup access point.
    pub portal_url: Option<String>,
    /// True while the e-paper panel reports BUSY (refreshing).
    pub display_busy: bool,
    pub display_refreshes: u64,
    pub boot_count: u32,
    /// Number of completed `Command::Press` presses.
    pub presses_done: u64,
    pub firmware: String,
    pub turbo: bool,
}

impl Default for Status {
    fn default() -> Self {
        Status {
            state: RunState::Running,
            sim_time_ns: 0,
            mips: 0.0,
            speed_ratio: 0.0,
            battery_mv: 4100,
            button_down: false,
            wifi_available: true,
            wifi_connected: false,
            ip: None,
            portal_url: None,
            display_busy: false,
            display_refreshes: 0,
            boot_count: 0,
            presses_done: 0,
            firmware: String::new(),
            turbo: false,
        }
    }
}

/// Serial console output, split into lines.
#[derive(Default)]
pub struct Console {
    pub lines: VecDeque<String>,
    partial: Vec<u8>,
    /// Total lines ever pushed (lets viewers detect new output cheaply).
    pub total: u64,
}

impl Console {
    /// Lines with absolute index >= `since` still in the buffer, as (index, line).
    pub fn lines_since(&self, since: u64) -> Vec<(u64, String)> {
        let first = self.total - self.lines.len() as u64;
        let start = since.max(first);
        self.lines
            .iter()
            .skip((start - first) as usize)
            .enumerate()
            .map(|(i, l)| (start + i as u64, l.clone()))
            .collect()
    }
}

impl Console {
    const MAX_LINES: usize = 20_000;

    pub fn push_bytes(&mut self, bytes: &[u8]) {
        for &b in bytes {
            match b {
                b'\n' => {
                    let line = String::from_utf8_lossy(&self.partial).trim_end_matches('\r').to_string();
                    self.partial.clear();
                    self.push_line(line);
                }
                _ => self.partial.push(b),
            }
        }
    }

    /// A line generated by the simulator itself (not the guest).
    pub fn push_sim(&mut self, msg: &str) {
        self.push_line(format!("[sim] {msg}"));
    }

    fn push_line(&mut self, line: String) {
        self.lines.push_back(line);
        self.total += 1;
        while self.lines.len() > Self::MAX_LINES {
            self.lines.pop_front();
        }
    }
}

/// Everything a front-end needs. Cheap to clone.
#[derive(Clone)]
pub struct SimHandle {
    pub frame: SharedFrame,
    pub console: Arc<Mutex<Console>>,
    pub status: Arc<Mutex<Status>>,
    pub commands: Sender<Command>,
}

impl SimHandle {
    pub fn send(&self, c: Command) {
        let _ = self.commands.send(c);
    }
}

/// The emulator thread's side of the handle.
pub struct SimPorts {
    pub frame: SharedFrame,
    pub console: Arc<Mutex<Console>>,
    pub status: Arc<Mutex<Status>>,
    pub commands: Receiver<Command>,
}

pub fn channel(frame: SharedFrame) -> (SimHandle, SimPorts) {
    let (tx, rx) = crossbeam_channel::unbounded();
    let console = Arc::new(Mutex::new(Console::default()));
    let status = Arc::new(Mutex::new(Status::default()));
    (
        SimHandle { frame: frame.clone(), console: console.clone(), status: status.clone(), commands: tx },
        SimPorts { frame, console, status, commands: rx },
    )
}
